config/routes.rb
Rails.application.routes.draw do

  devise_for :students, :controllers => { :registrations => :registrations }
  devise_for :teachers, :controllers => { :registrations => :registrations }

  root                   'pages#splash'
  get  'home'         => 'pages#home'
  get  'about'        => 'pages#about'
  get  'contact'      => 'pages#contact'
  get  'teachers'     => 'teachers#index'
  get  'teachers/:id' => 'teachers#show', as: :teacher
  get  'students/:id' => 'students#show', as: :student
  resources :locations

end

app/views/pages/about.html.erb
<h1>About</h1>
<p>This application should eventually have the following features:</p>
<h2>Teachers</h2>
<ul>
  <li>Create up a public profile.</li>
  <li>Connect with teaching locations and add new ones.</li>
  <li>Submit their availbility for lessons.</li>
  <li>Receive student bookings.</li>
  <li>Create lesson records.</li>
  <li>Receive payment.</li>
  <li>Access the forum.</li>
  <li>Access resources for teachers.</li>
</ul>
<h2>Students</h2>
<ul>
  <li>Find a teacher sorted by location, rating, availbility.</li>
  <li>View teaching locations.</li>
  <li>View teacher and location reviews and availability.</li>
  <li>Book and pay for a lesson.</li>
  <li>Access lesson records.</li>
  <li>Revise new vocabulary and phrases with smart flash cards.</li>
  <li>Upload audio recording to lesson record.</li>
  <li>Access the forum.</li>
  <li>Access resources for students.</li>
</ul>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  This site is currently a work in progress. For more information contact <%= link_to "Sheldon Johnson", "http://drzel.github.io/cv/" %>.
</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if teacher_signed_in? %>
<!-- teacher dashboard -->
      <h1>Teacher dashboard</h1>
      <div class="col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Locations</h3>
          </div>
          <div class="panel-body">
            <% current_teacher.locations.each do |location| %>
              <div class="media">
                <div class="media-left">
                  <%= image_tag location.avatar.url(:thumb), class: "media-object" %>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <%= link_to location.name, edit_location_path(location) %>
                  </h4>
                  <ul class="list-unstyled">
                    <li><span class="glyphicon glyphicon-home"></span>
                      <%= link_to "Homepage", location.homepage %>
                    </li>
                      <li><span class="glyphicon glyphicon-map-marker"></span>
                        <%= link_to("http://maps.google.com/?q=#{location.street_address} #{location.ward} #{location.prefecture} #{location.city}") do %>
                          <%= "#{location.street_address}, #{location.ward}, #{location.prefecture}, #{location.city}" %>
                      </li>
                    <% end %>
                  </ul>
                  <p><%= link_to "Delete location", location, method: :delete, data: {confirm: "Are you sure?" } %></p>
                </div>
              </div>
            <% end %>
            <div class="media">
              <%= link_to "Add a location", new_location_path, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% elsif student_signed_in? %>
    <!-- student dashboard -->
      <h1>Student dashboard</h1>
    <% else %>
    <!-- visitor page -->
      <div class="center jumbotron">
        <div class="row">
          <div class="col-md-8 col-sm-offset-0 col-sm-7 col-xs-offset-1 col-xs-10">
            <h1>English Over Coffee</h1>
            <p>
              An app for English as a second language tutors and students to keep track of
              their lessons, including bookings, vocabulary, phrases, pronunciation etc.
            </p>
            <p>
              <%= link_to "Find teachers", teachers_path, class: "btn btn-primary btn-lg" %>
              <%= link_to "Browse locations", locations_path, class: "btn btn-primary btn-lg" %>
            </p>
          </div>
          <div class="col-md-4 col-sm-offset-0 col-sm-5 col-xs-offset-1 col-xs-10">
            <h3>Student sign up</h3>
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
              <%= devise_error_messages! %>
              <div class="form-group">
                <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Your email" %>
              </div>
              <div class="form-group">
                <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %>
                <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Create password" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Confirm password" %>
              </div>
              <div class="form-group">
                <%= f.submit "Sign up", class: "btn btn-lg btn-block btn-primary" %>
              </div>
              <%= link_to "Sign up as a teacher", new_teacher_registration_path %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
    </div>

app/views/pages/splash.html.erb
<div class="container">
  <div class="col-xs-12">
    <h1>English Over Coffee</h1>
    <p>
      An app for English as a second language tutors and students to keep track of their lessons, including bookings, vocabulary, phrases, pronunciation etc.
    </p>
    <p>
      This site is currently a work in progress. For more information contact <%= link_to "Sheldon Johnson", "http://drzel.github.io/cv/" %>.
    </p>
    <p>
      <%= link_to "Okay show me the site.", home_path %>
    </p>
  </div>
</div>