config/routes.rb
Rails.application.routes.draw do

  devise_for :students, :controllers => { :registrations => :registrations }
  devise_for :teachers, :controllers => { :registrations => :registrations }

  root                   'pages#splash'
  get  'home'         => 'pages#home'
  get  'about'        => 'pages#about'
  get  'contact'      => 'pages#contact'
  get  'teachers'     => 'teachers#index'
  get  'teachers/:id' => 'teachers#show', as: :teacher
  get  'students/:id' => 'students#show', as: :student
  resources :locations

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr />
  <nav>
    <ul class="nav navbar-nav">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("eoc-logo.png", alt: "English Over Coffee", class: "navbar-left"), root_path, id: "logo" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <% if signed_in? %>
          <ul class="nav navbar-nav visible-xs">
            <li class="inline navbar-avatar">
              <% if teacher_signed_in? %>
                <%= image_tag(current_teacher.avatar.url(:thumb)) %>
              <% elsif student_signed_in? %>
                <%= image_tag(current_student.avatar.url(:thumb)) %>
              <% end %>
            </li>
            <li class="inline-last">
              <p class="navbar-text">
                <% if teacher_signed_in? %>
                  <%= link_to "#{current_teacher.first_name} #{current_teacher.last_name}", teacher_url(id: current_teacher.id) %>
                <% elsif student_signed_in? %>
                  <%= link_to "#{current_student.first_name} #{current_student.last_name}", student_url(id: current_student.id) %>
                <% end %>
              </p>
            </li>
          </ul>
        <% end %>
        <ul class="nav navbar-nav">
          <% if teacher_signed_in? %>
            <li><%= link_to "Students", '#' %></li>
          <% end %>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Teachers", teachers_path, id: "browse-teachers" %></li>
              <li><%= link_to "Locations", locations_path %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <% if teacher_signed_in? %>
              <li class="hidden-xs">
                <p class="navbar-text">
                  <%= link_to "#{current_teacher.first_name} #{current_teacher.last_name}", teacher_url(id: current_teacher.id) %>
                </p>
              </li>
              <li class="navbar-avatar hidden-xs"><%= image_tag(current_teacher.avatar.url(:thumb)) %></li>
              <li><%= link_to "Edit profile", edit_teacher_registration_path %></li>
              <li><%= link_to "Log out", destroy_teacher_session_path, :method => :delete %></li>
            <% elsif student_signed_in? %>
              <li class="hidden-xs">
                <p class="navbar-text">
                  <%= link_to "#{current_student.first_name} #{current_student.last_name}", student_url(id: current_student.id) %>
                </p>
              </li>
              <li class="navbar-avatar hidden-xs"><%= image_tag(current_student.avatar.url(:thumb)) %></li>
              <li><%= link_to "Edit profile", edit_student_registration_path %></li>
              <li><%= link_to "Log out", destroy_student_session_path, :method => :delete %></li>
            <% end %>
          <% else %>

            <li class="dropdown visible-xs">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign up <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Students", new_student_registration_path %></li>
                <li><%= link_to "Teachers", new_teacher_registration_path %></li>
              </ul>
            </li>

            <li class="dropdown visible-xs">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign in <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Students",  new_student_session_path %></li>
                <li><%= link_to "Teachers",  new_teacher_session_path %></li>
              </ul>
            </li>

            <div class="btn-group hidden-xs">
              <button type="button" class="btn btn-primary dropdown-toggle navbar-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sign up <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Students", new_student_registration_path, :id => "student-sign-up" %></li>
                <li><%= link_to "Teachers", new_teacher_registration_path, :id => "teacher-sign-up" %></li>
              </ul>
            </div>

            <div class="btn-group hidden-xs">
              <button type="button" class="btn btn-default dropdown-toggle navbar-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sign in <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Students",  new_student_session_path %></li>
                <li><%= link_to "Teachers",  new_teacher_session_path %></li>
              </ul>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>English Over Coffee</title>
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1, user-scalable=no"> 
    <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>